spring:
  application:
    name: SportyShoes
  datasource:
    url: jdbc:h2:file:F:/h2db/sportyshoes/db
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update  
  h2:
    console:
      enabled: true
      path: /h2-sportyshoes 
      
server:
  port:8080


